updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  MEMBER: 1
maxRequestedChanges:
  NONE: 0
blockingLabels:
  - blocked

rules:
  - requiredLabels:
      - merge
    minApprovals:
      MEMBER: 0