name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: "🚀 Features"
    when:
      labels:
        - "feature"
        - "enhancement"
  - title: "🐛 Bug Fixes"
    when:
      - labels:
          - "bug"
          - "fix"
          - "bugfix"
      - labels:
          - "regression"
  - title: '🛠️ Maintenance'
    when:
      - labels:
          - "chore"
  - title: '⚠️ Breaking changes'
    when:
      - labels:
          - "breaking-change"
  - title: '🐌 Performance'
    when:
      - labels:
          - "performance"
  - type: "pre-exclude"
    when:
      label: "skip-changelog"

change-template: | 
  - ### $TITLE @$AUTHOR (#$NUMBER)
    $BODY
    
  
template: |
  # 🎉 DavidGroup.Core.Utilities $RESOLVED_VERSION

  ## Changes

  $CHANGES
  
  ### Contributors

  $CONTRIBUTORS