name: CI of dev branch

on:
  push:
    branches: [ "dev" ]

jobs:
  test:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
              8.0.x
              9.0.x
              10.0.x

      - name: Test
        working-directory: ./
        run: dotnet test --logger:trx --logger:GitHubActions

  publish:
    name: Publish dev package
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
              8.0.x
              9.0.x
              10.0.x

      - name: Clean package cache as a temporary workaround for https://github.com/actions/setup-dotnet/issues/155
        working-directory: ./
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      - name: Compute version info
        id: version
        run: |
          prefix=$(xmllint --xpath "string(//Project/PropertyGroup/VersionPrefix)" Directory.Version.props)
          branch="${{ github.head_ref || github.ref_name }}"
          revision=$(printf "%05d" "${{ github.run_number }}")

          short_branch="${branch:0:10}"
          short_branch=$(echo "$short_branch" | sed 's/[^a-zA-Z0-9-]//g')

          suffix="${short_branch}-${revision}"
          echo "suffix=$suffix"           >> "$GITHUB_OUTPUT"

          echo "Package version prefix is $prefix"
          echo "Package version suffix is $suffix"
          echo "Package version is $prefix-$suffix"

      #########################################################################################
      # Uncomment if signing is needed for NuGet package.
      #########################################################################################
      #
      # - name: Obtain SNK
      #   id: obtain_snk
      #   uses: timheuer/base64-to-file@v2
      #   with:
      #     fileName: 'SigningKey.snk'
      #     encodedString: ${{ secrets.SNK_BASE64 }}

      - name: Pack
        # Use this command if signing is needed for NuGet package.
        # run: dotnet pack -c Release --version-suffix="${{ steps.version.outputs.suffix }}" /p:ContinuousIntegrationBuild=true /p:AssemblyOriginatorKeyFile=${{ steps.obtain_snk.outputs.filePath }} /p:ShouldSignAssembly=true
        run: dotnet pack -c Release --version-suffix="${{ steps.version.outputs.suffix }}" /p:ContinuousIntegrationBuild=true

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: davidgroup

      - name: Publish package to NuGet.org
        run: dotnet nuget push **/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
