name: Release

on:
  release:
    types: [ published ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      #########################################################################################
      # Uncomment if signing is needed for NuGet package.
      #########################################################################################
      #
      # - name: Obtain SNK
      #   id: obtain_snk
      #   uses: timheuer/base64-to-file@v2
      #   with:
      #     fileName: 'SigningKey.snk'
      #     encodedString: ${{ secrets.SNK_BASE64 }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
              8.0.x
              9.0.x
              10.0.x

      - name: Clean package cache as a temporary workaround for https://github.com/actions/setup-dotnet/issues/155
        working-directory: ./
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      - name: Pack
        working-directory: ./
        # Use this command if signing is needed for NuGet package.
        # run: dotnet pack -c Release /p:ContinuousIntegrationBuild=true /p:AssemblyOriginatorKeyFile=${{ steps.obtain_snk.outputs.filePath }} /p:ShouldSignAssembly=true
        run: dotnet pack -c Release /p:ContinuousIntegrationBuild=true

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: DavidGroupSolutions

      - name: Publish package to NuGet.org
        run: dotnet nuget push **/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Upload Artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} out/*.nupkg --clobber
          gh release upload ${{ github.event.release.tag_name }} out/*.snupkg --clobber
